version: "3"

services:
  mysql:
    image: mysql:5.7.29
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: always

    # mongodb:
  #   container_name: test-mongodb
  #   image: mongo:latest
  #   environment:
  #     - MONGODB_DATABASE="test"
  #   ports:
  #     - 27017:27017
  # zookeeper:
  #   container_name: test-zookeeper
  #   hostname: zookeeper
  #   image: confluentinc/cp-zookeeper:5.3.2
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
